# Generated by Django 4.0.1 on 2022-01-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_alarm_repeat_alter_alarm_repeat_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='status',
            field=models.CharField(blank=True, default='Not taken', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='turned_on',
            field=models.CharField(blank=True, default='On', max_length=2, null=True),
        ),
    ]
