# Generated by Django 4.0.1 on 2022-01-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_alarm_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='time',
            field=models.CharField(max_length=32),
        ),
    ]
